### ISSUE TITLE
Static rendering of grades/roster on course home page slows down the page

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#102]
Currently, the course home page has tabs, but the full content of each tab is completely generated on page load.  Because of the potentially large content in the grades and roster tabs (particularly for instructors), page loads can be really slow because of this.

Instead, the content for these tabs should only be generated dynamically when the tab is visited, rather than on page load.  The default tab (which shows workouts) can be generated on page load, but the other tabs should be dynamically loaded via ajax when the tab is first visited.

**Comment by ayaankazerouni** [comment]
Ok, this is done. Data is loaded only when the tab is opened for the first time, for all tabs except the workouts tab. Each tab's content is now moved to a partial. Closing for now.

**Comment by ayaankazerouni** [comment]
Ignore commit c3fe63cff74b7901e6c99fe9513e26d523bf9957, I mistype 102 instead of 103 in the message.
