### ISSUE TITLE
Improve exercise search in workout edit sidebar

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#103]
It looks like searching for exercises when editing a workout may only search tags.  Adding an exercise title word doesn't work.  We should enhance this so using words from titles and/or exercise ID numbers (such as X10) work.

I'm unsure if the sidebar uses a different search mechanism than the gym's index page.

Also, searching for exercises when editing a workout should include the author's private exercises, not just public exercises from the gym.

**Comment by ayaankazerouni** [comment]
See commit c3fe63cff74b7901e6c99fe9513e26d523bf9957 (erroneously labeled issue #102 in the message).

You can search by exercise title fragments, or by exact id by typing 'X{id}'. For each 'X{id}' style search term, you will get only one result. Closing for now.

**Comment by ayaankazerouni** [comment]
TODO:
* No constraints on the date pickers
* Change date picker controls entirely -- use something that lets the user use the keyboard
* Fix background-color issue on the sidebar
* Search -- message that says "no results, showing all exercises"
