### ISSUE TITLE
LTI - can possibly not find a user correctly

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#107]
If a user has changed their email on an LMS, CodeWorkout won't be able to find them using just the email address and will potentially create an extra user.

Fix: Use the LTI user_id param to find a user. If that fails, use the lis_email param, and then the canvas_login param. Either way, once a user is in hand (new or existing), add the user_id to the database, in a separate table (LTI User Ids). The table should have three fields: user_id, lti_user_id, consumer_key.

**Comment by s-edwards** [comment]
That should be lms instance id, not consumer_key.

**Comment by ayaankazerouni** [comment]
Right, yeah. I created this issue before that last part of the conversation.

**Comment by ayaankazerouni** [comment]
Done. Closing until further issues arise.
