### ISSUE TITLE
Fix exercise thumbnail icons

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#11]
Exercise thumbnails (both small and large) currently include an icon.  Right now, there is one fixed icon for all thumbnails, but the icon should be based on the exercise type (MC = glyphicon-th-list, coding = fa-file-code-o or fa-keyboard-o?) instead.

**Comment by pmk1433** [comment]
Done, though the latter two icons are missing.

**Comment by s-edwards** [comment]
Icons were OK.  The title was in the wrong place.  Also, there are two styles of thumbnails (sm for use in the sidebar, and lg for use in the main content area.  I ported the changes over to the other one so both are now fixed.
