### ISSUE TITLE
Broken Multiple Choice link

### ISSUE THREAD

**Issue by kbuffardi** [web-cat/code-workout#126]
I'm getting an error:

> ActionController::UrlGenerationError No route matches {:action=>"practice", :controller=>"exercises", :id=>nil} missing required keys: [:id]

...from the home page when I click on the Multiple Choice link to the URL: https://codeworkout.cs.vt.edu/gym/exercises/any?question_type=1

I was logged in when this happened. See following screen grab:

![screen shot 2018-01-28 at 8 43 19 pm](https://user-images.githubusercontent.com/8324410/35493969-22b17052-046c-11e8-987b-672c924e5bfb.png)

**Comment by ayaankazerouni** [comment]
Fixed on the staging branch. There were no public MCQs. I added an appropriate message if a public exercise with the right question_type/language filter is not found. But we probably should have some public MCQs if that link is on the home page.

**Comment by s-edwards** [comment]
Ayaan, can you do a search real quick and see which MCQs aren't associated with the "Big Java" textbook? We should probably review those that seem most promising for making public.

Incidentally, we should probably also provide a way to filter by question type in the gym ... and also add tag clouds there like we always wanted (well, after SIGCSE anyway).

**Comment by ayaankazerouni** [comment]
Looks like roughly half the MCQs (53 / 107) are not associated with Big Java. A cursory glance at their external_ids makes it look like a lot of them (maybe all) belong to assignments or exams.

**Comment by kbuffardi** [comment]
Do only certain users have permissions to add new exercises? I've added [a course](https://codeworkout.cs.vt.edu/courses/csuc/csci111/spring-2018) with my [account](https://codeworkout.cs.vt.edu/users/kbuffardi@mail.csuchico.edu) but while I see how to create a new workout, I don't see any links/buttons to create new exercises. I even tried to sneak my way to the right URL but going to https://codeworkout.cs.vt.edu/gym/exercises/new redirects me to the homepage with the error message:

>  You are not authorized to access that page.

If I can have access to create exercises, I'll start adding some for my class

**Comment by ayaankazerouni** [comment]
Closing.

@kbuffardi, right now, most users are not authorised to create new exercises, but we hope for that to not be the case soon.
