### ISSUE TITLE
Student completetion of LTI assignment not updating

### ISSUE THREAD

**Issue by tycrowe** [web-cat/code-workout#142]
Good afternoon, 

I recently completed my institutions final strides towards fully integrating CodeWorkout with Canvas but I've reached an impasse. When a student completes a workout, the left hand side of the assignment doesn't update despite the feedback showing completion. Note, the left hand side of the assignment DOES update when the instructor completes the workout. I imagine this is the reason behind why the Canvas gradebook isn't updating properly.

![codeworkout-problem1](https://user-images.githubusercontent.com/35441264/50788995-f3fff180-1288-11e9-8863-fd5da8a6ca35.PNG)

Any insights on to why this may be happening?

**Comment by ayaankazerouni** [comment]
Sorry for the (extremely) delayed response.

> When a student completes a workout, the left hand side of the assignment doesn't update despite the feedback showing completion.

The score was being updated on the backend, but not showing up on the sidebar.

> I imagine this is the reason behind why the Canvas gradebook isn't updating properly.
Maybe not. We recently had some troubles sending scores back to Canvas, but it was a certificate issue, not a score-saving issue.

Either way, both issues should no longer be present. I'm closing this issue, please reopen or open a new one if you still notice anything funny.
