### ISSUE TITLE
Which License does this project possess?

### ISSUE THREAD

**Issue by coolbrg** [web-cat/code-workout#145]
Hi

I came across this nice website https://codeworkout.cs.vt.edu/ and found it is open source.
But then found LICENSE missing in the project.

Would be great if you attach a license to it.

Thanks

**Comment by s-edwards** [comment]
Good point--the license is displayed on the app's license page, but isn't in the root of the repo. It is licensed under the AGPL v3. We'll add a LICENSE file in the root as time permits.

**Comment by coolbrg** [comment]
Thanks @s-edwards . Really appreciated 😄
