### ISSUE TITLE
SSL Cerificate from https://codeworkoutdev.cs.vt.edu/ has expired

### ISSUE THREAD

**Issue by axel1200** [web-cat/code-workout#149]
-

**Comment by ayaankazerouni** [comment]
Hello – That's the staging server, where we test things out before deploying changes to the main site, which is at [codeworkout.cs.vt.edu](https://codeworkout.cs.vt.edu) (notice there is no "dev" in the URL)

**Comment by s-edwards** [comment]
I have the cert, but it hasn't been installed on the staging server yet. Ayaan, do you need it on the staging server to test with ssl?

**Comment by ayaankazerouni** [comment]
Yes, it does make things easier especially for LTI stuff.

**Comment by ayaankazerouni** [comment]
Fixed by @s-edwards
