### ISSUE TITLE
vagrant installation errors

### ISSUE THREAD

**Issue by jhudsy** [web-cat/code-workout#154]
I am trying to install code-workout via Vagrant as specified in the readme.md file. However, vagrant up seems to return many many errors, and "rails server" then doesn't run. Attached is the output of the vagrant up command.
[err.txt](https://github.com/web-cat/code-workout/files/4045321/err.txt)

**Comment by ayaankazerouni** [comment]
I believe you need bundler version 1.17.3 to get this to work. I will need to track down the source of this requirement and fix it soon, but for now this should get you going.

**Comment by ayaankazerouni** [comment]
Closing. For future reference, please use the Docker workflow now specified in the README
