### ISSUE TITLE
HTML parsing issues

### ISSUE THREAD

**Issue by TheGregor** [web-cat/code-workout#159]
When passed HTML formatting tags (e.g. < pre >< /pre >, < code >< /code >), CodeWorkout prints them as plaintext concatenated to the answer options:

![example](https://user-images.githubusercontent.com/22732951/83363812-6a176380-a36a-11ea-91c2-3a8d135106b6.jpg)

Is there anything that can be done to resolve this so that the answers retain their desired formatting?

Thanks--

**Comment by ayaankazerouni** [comment]
Thanks for reporting! I've fixed it in the development branch, and this should be deployed soon.

**Comment by ayaankazerouni** [comment]
This is now deployed

**Comment by TheGregor** [comment]
Thank you!  I just checked and everything looks great.  I really appreciate the dedication!
