### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#16]
Priyanka did some prototype screens that included breadcrumbs, a feature we had discussed as useful.  These should be included for Torch.  We need to figure out the appropriate strategy and build it into our pages/controllers now, instead of trying to add it later.

**Comment by pmk1433** [comment]
I am not sure what the breadcrum prototype that Priyanka designed looks like and I am not able to find it on Dropbox either. If you have it, can you please e-mail it to me?

**Comment by s-edwards** [comment]
See Mockups/workout_practice2.html on dropbox.  You'll see something like the attached image.
![screen shot 2015-03-16 at 8 22 44 pm](https://cloud.githubusercontent.com/assets/1132008/6679150/5b9693da-cc1a-11e4-9348-932b22ce144b.png)

All breadcrumbs should start with either "Gym >" or a specific semester/course, like "Spring 2015 > CS 1114 >".  If you're viewing a specific workout, or an exercise within a workout, then the workout comes next.  Finally, the exercise (if you're looking at one) comes last.  Similar patterns would need to be used for search result pages, for course pages, and for the individual's profile page.  That should be enough for a start, but ask questions if they come up.

**Comment by pmk1433** [comment]
Added the breadcrumbs, though they don't look pretty.

**Comment by s-edwards** [comment]
I only see them added on the exercises/practice view.  Did you put them anywhere else?  The intent was for them to go on most pages (i.e., workouts, courses, etc., also perhaps the gym).  As for "pretty", they should follow the markup here: http://getbootstrap.com/components/#breadcrumbs, and should probably be in a separate partial.  It would be nice it we had one partial for all breadcrumbs that could be placed in the appropriate top-level layout, but since the objects available for generating them depend on the specific model being viewed, having a separate breadcrumbs partial for exercises, for workouts, and for courses is probably sufficient for now.

**Comment by pmk1433** [comment]
I am not exactly sure what the breadcrum for a course page will look like because it is a root/start in itself right?

**Comment by pmk1433** [comment]
The breadcrumbs are in place for workouts and exercises, waiting for word on the rest.

**Comment by pmk1433** [comment]
Breadcrumbs redone according to the specification given on paper. Please check it out and let me know if there is anything else needed to be done with regard to this.

**Comment by s-edwards** [comment]
Breadcrumbs are now working in master the way they are supposed to.  Any specific pages that have missing or incorrect breadcrumbs should be filed as separate issues (bugs) now.  Thanks.
