### ISSUE TITLE
What is the limit on workout names?

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#17]
The Workout model has a validation rule that requires workout names to be between 1-50 characters in length.  The corresponding validation error message describes the same thing, and limits the characters that can appear in workout names.  However, the database schema does not have this length limit.

Is this length limit necessary for some reason, or can it be removed?  Similarly, is the character set limitation necessary for some reason, or can it be removed?

**Comment by pmk1433** [comment]
It was a limit that I inherited when I came into CodeWorkout.  We had earlier discussed whether there was a need for such a limit. I am just extending the limit to 500 because, I think we might need to set an upper bound in the future and we can use this as a placeholder for the time being.

Sorry for missing this.

**Comment by s-edwards** [comment]
OK, but 500 won't work, either.  The schema definition says the corresponding db field is a "string" which translates to a default max size of 255.  However, none of the other plain string fields in other objects have max length validations.  So either the validation is incorrect and unnecessary, or max size 255 needs to be included in validation rules for all of those other attributes in every other model as well.  For now, I suggest removing the max part of the validation.

**Comment by pmk1433** [comment]
Ok, I will remove the max title limit on Workouts.

**Comment by s-edwards** [comment]
Sounds good.

**Comment by s-edwards** [comment]
Oops--closed too soon.  Kevin, do you have any insight into why there are character set limits on workout names here?  ATM, I don't see any reason for them ...

**Comment by pmk1433** [comment]
Er, can we close this one now?

**Comment by s-edwards** [comment]
Yes.
