### ISSUE TITLE
Redesign edit form for workouts

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#19]
Use the rough prototypes created by Priyanka as a guide.

**Comment by pmk1433** [comment]
Reworked the priority and milestone of this deliverable based on the discussion on 5/5. Torch will have pre-entered exercises/workouts and we have shifted the focus on delivering instructor creatable/editable exercises/workouts for Avalanche (slated for Summer-II).

**Comment by pmk1433** [comment]
The Workout edit form now works in the most basic manner. Looks bad as ever. Need to re-design it as per mockups.

**Comment by ayaankazerouni** [comment]
TODO:
* No constraints on the date pickers
* Change date picker controls entirely -- use something that lets the user use the keyboard
* Fix background-color issue on the sidebar
* Search -- message that says "no results, showing all exercises"

**Comment by ayaankazerouni** [comment]
Update: almost done with these changes. Using this datepicker control: https://chmln.github.io/flatpickr/#example-basic

@s-edwards, let me know if you don't like that datepicker.

**Comment by s-edwards** [comment]
Yes, this date picker looks much better than the current one.

**Comment by ayaankazerouni** [comment]
Can't add the same exercise to a workout multiple times?
