### ISSUE TITLE
Should sm and lg thumbnails be merged?

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#20]
There are currently two styles of thumbnails for both exercises and workouts.  The original intent was for one to be a smaller sidebar-only version, while the other would perhaps contain more content/detail for use in the main content area.

However, at present, these two are virtually identical except for the css tag of the main element.  It would be possible to merge these pairs into one view per model instead of having two.  An additional view parameter could be used for indicating lg vs. sm, for customizing css tags, adjusting teaser text length, etc., if there are no significant logic differences between the two views.  Should we do this?

**Comment by pmk1433** [comment]
Probably yes but I am chary about actually doing it till we are pretty certain that we won't be needing the two of them to be separate entities.

**Comment by s-edwards** [comment]
They are now merged, and support a "size" parameter.
