### ISSUE TITLE
Move to FriendlyId for slug-based url support

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#25]
Replace the roll-your-own "url_part" support in various model classes with FriendlyId support instead.  Also, move from having all models use top-level urls, to providing scope-based urls that match logical breadcrumbs instead.

**Comment by pmk1433** [comment]
Needs some clarifications on this, probably will get it from you this week to see if I can contribute to this as well.

**Comment by s-edwards** [comment]
I just merged some changes into master that include a completely rewritten controller for Term that illustrates how I want to do this (and also how I want to DRY up some of the controllers, how I want to the CanCan enforcement to work, and how I want to limit the customer-facing views/routes available now that the admin backend is available).  You can pull and run it.  Go to /terms, and look at the url links now used for the "show" buttons.  Click one, and see the url used for a specific term.  It should give you an idea of what I mean (replacing numeric id numbers with humanized symbolic names in URLs for model objects).  There's very little code needed to support it in this mode.  Ironically, its now the biggest chunk of code in the TermController, even though it is quite small in size (because that controller is now super DRY).

**Comment by s-edwards** [comment]
This is working for all but workouts now.
