### ISSUE TITLE
Sidebar throws an error when there is no current workout

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#26]
The error is:

ActiveRecord::RecordNotFound (Couldn't find Exercise without an ID):
  app/views/layouts/_sidebar.html.haml:14:in `_app_views_layouts__sidebar_html_haml___...'
 
The sidebar needs to be fixed so that it does not assume a current workout is actively being practiced.

**Comment by pmk1433** [comment]
Made some fixes. Looks about working right.

**Comment by s-edwards** [comment]
No, was still broken.  The problem was that, if session[:leaf_exercises] was not defined, the Exercise.find() call would throw an error.  I fixed it in my branch and will merge it into master.  The fix eliminates the error, but the sidebar still needs to be revised to show appropriate content (instead of appearing empty) when there is no current workout.  I think we need to settle on how info regarding the current workout is stored and handled first.
