### ISSUE TITLE
Huge number of DB fetches per page load

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#27]
On pages where the sidebar has workout contents, or on search results pages that show thumbnails of exercises or workouts, a large number of DB fetches are generated.  This is because of the cascading nature of the relationships involved.  Showing one thumbnail requires accessing many objects--for each tag, as well as for the user's latest attempt or score, etc.  However, if this results in 1/2-1 dozen fetches for one thumbnail, that is multiplied by the number of thumbnails being rendered.  We should consider preloading tags (at least) in the fetches that generate the list of thumbnails to render.

Ideally, the relationships that lead to the displayed lists of thumbnails should be defined to include the tags relation as preloaded.

**Comment by pmk1433** [comment]
Ouch, looks like need to work more to optimize this one.

**Comment by pmk1433** [comment]
Done and dusted.
