### ISSUE TITLE
Boolean checkboxes in edit forms don't work

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#3]
Boolean checkboxes for attributes in formtastic forms don't seem to work correctly.  Is there javascript missing, or is it some other problem?

According to Krishnan, this could be due to javascript code that auto-clears all checkboxes.  See application.js line 79.  This should be removed (and the root problem fixed).

**Comment by kbuffardi** [comment]
I remember running into this problem at least on the practice page. No configurations of the formtastic checkboxes would make them "unchecked" by default. I can't remember if I was the one who added the auto-clear js but it's definitely just a workaround and if we can figure out making checkboxes unchecked by default within the form, that'd be ideal.

IIRC, formtastic generates those checkboxes and selects them by default because they are required to have values in the table.

**Comment by s-edwards** [comment]
OK, it looks like the root problem is that the practice page is really an entry form for a new attempt, but the page itself uses the formtastic tools to present what amounts to an edit form for (a part of) the exercise itself.

The list of choices on the practice page are shown with what amounts to "f.input :choice_ids, collection: @answers, ...".  This fragment says to create an input control where (a) the choices come from the array @answers (which is generated from the exercise's list of available choices), and the /values/ for the selected choices come from the exercise's actual choices relationship.  Naturally, /all/ of the choices have a relationship with the parent exercise, so they are /all/ checked when the page loads.  Basically, formtastic is actually doing its job correctly, but the page is written wrong.

Fixing this means changing the form, since this set of radio buttons/check boxes is not in any way a form for editing the relationships in the exercise itself.

In the mean time, I've commented out the input clearing javascript fragment in application.js, which lets everything else work as expected (so it was definitely the culprit).  I'll also work on revising the practice page to fix the practice form so it does what it needs to.

**Comment by s-edwards** [comment]
OK, problem solved (or hacked :-)).  I added a dummy scratch/empty exercise in the practice action, and then used semantic_fields_for to generate the fields, with the choices array generated as before in @answers.  This fixed the problem of which boxes were initially checked, although it slightly changed the parameter dictionary in the form submissions (code fixed for that).  The fix is working and is checked in on my branch, and will be merged into master on my next merge.
