### ISSUE TITLE
Figure out SSE AJAXy feedback push

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#33]
Need to figure out how to do server-side push to students to receive feedback on their exercise practice on development. This is done to give indications for issue #15.

**Comment by pmk1433** [comment]
This now works for the most part. However, the DB keeps getting locked when there are multiple threads trying to write to the same tables. Need to figure out what to do regarding this.

**Comment by s-edwards** [comment]
Confirmed working.
