### ISSUE TITLE
Add self-enrollment links to course offering lists

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#34]
On the pages that show lists of course offerings, we need to add self-enrollment links for those offerings that the current user is not enrolled in, if those offerings do allow self-enrollment.  These pages include:

/courses
/courses/&lt;organization&gt;
/courses/&lt;organization&gt;/&lt;term&gt;

In addition, we should modify the course show page (which is at /courses/&lt;organization&gt;/&lt;term&gt;/&lt;course&gt;) so that, if the current user is not enrolled, it shows the list of offerings including self-enrollment links/info, for those where self-enrollment is available.

Also, we need to update the course offerings model to include an optional cut-off date for self-enrollment.  New course offerings that allow self-enrollment should use use the end date of their associated term as the default cutoff date, but the instructor should be able to change this date.   After the specified date, self-enrollment should be closed (no longer available).

**Comment by pmk1433** [comment]
I have implemented this feature, though I believe I might have missed some of the views that you were intending. Can you please check this one out and let me know what else I need to do in this regard?

**Comment by pmk1433** [comment]
This feature is now more or less implemented according to the specifications. Please verify it in PROD once it has been checked in.

**Comment by s-edwards** [comment]
Let me know when it has been checked in.

**Comment by pmk1433** [comment]
Pushed. Note that most of the self-enrollment logic is now present in the self_enrollment partial in the course_offerings view.

**Comment by pmk1433** [comment]
Can this be closed out please?
