### ISSUE TITLE
Fix exercises_controller's evaluate method to work with new data model

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#35]
Update the evaluate action to use the new model for attempts.  The evaluate action should create the attempt, and create the corresponding prompt answer(s) from the field values, storing the answers.  Then the id for the newly created attempt is what get posted for the worker to process.

In addition, the code worker needs to be updated to use the new attempt model.

**Comment by pmk1433** [comment]
Evaluate now works properly for both mcqs and coding questions. Need to be merged though.

**Comment by pmk1433** [comment]
Done and done.
