### ISSUE TITLE
Double-check scoring behavior

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#38]
Ensure that the scores being calculated for individual exercises and for workouts are correct.  This needs to be tested with exercises where different test cases have different weights, and for workouts where different exercises are worth different numbers of points, and for workouts where some exercises are partially correct but not fully correct.

**Comment by pmk1433** [comment]
Workout scoring now works as it should but is not fully tested and pushed because of uncertainities in the test exercises.
