### ISSUE TITLE
Redo navigation of exercises in workouts

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#43]
Need to redo the way that a student navigates through the exercises in the workout. Currently, the list of 'remaining' exercises are maintained in params/session but this does not safeguard against situations where students might be jumping around workouts exercises. Need to develop a consistent mechanism that will suggest the next exercise that a student is led to by the 'Next exercise' link.

Probably be ought to be done as a model class method rather than a controller method.

**Comment by pmk1433** [comment]
Navigation is done through the individual exercises served by the next_exercise method in the Workout class.

**Comment by pmk1433** [comment]
Can this be reviewed in PROD and closed out?

**Comment by s-edwards** [comment]
Done.
