### ISSUE TITLE
Add roster upload support to roster tab on courses page

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#45]
Add a pythy-style button that supports manual enrollment of individual accounts or bulk upload of CSV files to the roster tab on the courses page.  There should be one button per course section, when multiple sections are shown (inside the loop over @course_offerings).

**Comment by pmk1433** [comment]
Reproachable lack of progress on this issue. Certainly should try to release this feature by the Republic milestone.

**Comment by ayaankazerouni** [comment]
Individual enrolment implemented. Working on roster upload.

**Comment by ayaankazerouni** [comment]
Roster upload working. Closing for now.
