### ISSUE TITLE
Implement enrollment deletion on roster tab of course show page

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#46]
There is already an "X", but it needs to be turned into an action that deletes the corresponding course enrollment and refreshes the corresponding table on the page.  Note that there may be multiple tables on the page if multiple sections are available, and the correct table must be refreshed.

**Comment by pmk1433** [comment]
I believe you have already taken care of most of this issue.

**Comment by pmk1433** [comment]
Best to have this feature implemented by the Republic deadline along with issue #45.

**Comment by ayaankazerouni** [comment]
This is implemented on the staging branch. @s-edwards, I delete the enrollment after showing a basic confirmation dialog. Deleting the enrollment doesn't delete any `attempts` or `workout_scores`. Instructors can delete students' enrollments only.

Can this be closed?
