### ISSUE TITLE
Fix kaminari paging of course rosters on roster tab of course show page

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#47]
There is already some setup for this on the page, but the problem is when multiple course sections are shown.  If there are multiple sections, they currently all use the same dom ID names for the tables, and for the paging controls.  That won't work.  Instead, those ID names need to be specific to each course offering.  Also, I ended up removing the roster partial, since it didn't seem to be doing anything useful--instead, we can probably go with just the row partial like Pythy.  However, this means the show.js.coffee view is out of sync and paging doesn't work at the moment.

**Comment by ayaankazerouni** [comment]
Roster tab shows at most 100 students in each section, with no page navigation links.

**Comment by ayaankazerouni** [comment]
Ok, this is fixed. This issue will close when `staging` is merged into `master`.
