### ISSUE TITLE
Implement relative rendering of workout thumbnails

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#50]
![thumbnails1](https://cloud.githubusercontent.com/assets/8754152/10120065/7173596c-6478-11e5-88cb-69e30fc22bbe.png)
![thumbnails2](https://cloud.githubusercontent.com/assets/8754152/10120067/718a86fa-6478-11e5-8e6c-c7ca446cf29d.png)
![thumbnails3](https://cloud.githubusercontent.com/assets/8754152/10120066/71852a52-6478-11e5-86b3-9eea41a99e6b.png)

Based on static_pages/thumbnail.html.haml

Rails relative time methods?

**Comment by pmk1433** [comment]
Triple verified that it works in my branch. Should work in PROD too.

**Comment by pmk1433** [comment]
I think this one should be closed out if it has been verified. The problems earlier faced by @s-edwards were partly due to the usage of Time.now instead of Time.zone.now

**Comment by s-edwards** [comment]
fixed.
