### ISSUE TITLE
Create a new model for individual deadline

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#51]
with user_id, workout_offering_id, soft_deadline, hard_deadline.
(for exceptions)

**Comment by pmk1433** [comment]
Implemented in my dev branch.

**Comment by s-edwards** [comment]
Merged with master and working.  We still need corresponding edit/management controls, though.

**Comment by pmk1433** [comment]
Closing this one out since corresponding edit/management controls are the concern of a new issue, not this one.
