### ISSUE TITLE
Fix the display of the CodeMirror area

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#52]
During the practice of the exercise, the CodeMirror area is display in a funky manner instead of the horizontal scrolling being done in a graceful manner. Probably need to fix how we are doing it with CodeMirror.

![cw-practice](https://cloud.githubusercontent.com/assets/8754152/10119605/9504498c-6468-11e5-8551-f6d4b7640ab8.png)

**Comment by s-edwards** [comment]
Is this still happening for you?  I'm not seeing it in either Chrome or Safari (on OS X).

**Comment by pmk1433** [comment]
Yes, this is still happening for me and for Ayshwarya too.

**Comment by s-edwards** [comment]
Fixed.  This was due to a CSS rule setting a minimum height for the code display region.
