### ISSUE TITLE
Fix the buggy scoring

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#53]
Currently for homework 4, the score is being displayed as a decimal with non-zero fractional part, even when the full score for a workout is achieved. For example, for user pmk1433@vt.edu the score for the homework is displayed as 100.3 whereas it should be 100.0

**Comment by pmk1433** [comment]
Round and re-total the score attempts for a Workout Score?

**Comment by pmk1433** [comment]
From what I have seen, this issue is fixed through code changes in the workout score model. Need to be verified in PROD.

**Comment by s-edwards** [comment]
Can you point to the method in the workout score model where this is fixed?

Also, we need to retroactively fix/re-total existing workout scores.

**Comment by pmk1433** [comment]
Most of the changes occured in the record_attempt method of the workout score model. I have tagged most of my code changes for this issue with appropriate commit messages so that they will be easy to find. 

I am thinking of writing a stand-alone static method in workout offering to retroactively to re-compute the scores but I am afraid that it might lead to some inadvertent data loss. Also, I am focussing on issue #19 for the time being.

**Comment by pmk1433** [comment]
I think this one should be closed out.
