### ISSUE TITLE
'Back to the Past' code in exercise practice

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#55]
Improve the practice page so that it pre-loads the student's last answer attempt for the current workout score, if any, instead of the pre-provided starter code, as well as the associated feedback.  That way, when a student leaves and then comes back to "resume" a question, they pick up where they left off.  Also, add a "reset" kind of button to the code area so they can clear their attempt and start over fresh with the pre-provided starter code if they need to.

**Comment by s-edwards** [comment]
Now fixed in master (changes to ExercisesController#practice, and to corresponding view).

**Comment by pmk1433** [comment]
Has this been pushed to PROD and verified there?

**Comment by s-edwards** [comment]
Yes.
