### ISSUE TITLE
Add an assignment review page

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#56]
Need to add a page similar to the practice page for reviewing one's answer once the workout is closed.  This would show the attempt used for scoring plus feedback, but be a non-editable code area without any "check my answer" button. This would be for when students are looking back over their work on an assignment after it has finished, and when they can no longer make new answers.

**Comment by pmk1433** [comment]
Implemented in my dev branch except for the readonly attribute in semantic forms not working. Looks horrible.

**Comment by pmk1433** [comment]
Can this issue be closed out now? I believe most of it is in place.

**Comment by s-edwards** [comment]
Yes, implemented.
