### ISSUE TITLE
Add current exercise score to exercise feedback display

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#57]
Add a radial progress bar showing the current score (same as in thumbnails) to the right of the "Feedback" title in the exercise feedback (generated in the sse/ajax_feedback view).

**Comment by pmk1433** [comment]
Implemented in my dev branch. Looks horrible.

**Comment by pmk1433** [comment]
Does not looks like it is fully integrated into PROD. Why not?

**Comment by s-edwards** [comment]
Fixed.
