### ISSUE TITLE
Re-implement the next exercise feature in exercise practice

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#58]
Need to add a 'Next Exercise' button to the exercise practice page so that students will be able to use it navigate from one exercise to another during the current workout (if it exists). This button should become the primary button in the page when the student gets a perfect score on that exercise, instead of the submit button.

**Comment by pmk1433** [comment]
Implemented in my dev branch. Looks horrible.

**Comment by pmk1433** [comment]
Since this is has been implemented in PROD, can we please close this one out?

**Comment by s-edwards** [comment]
We still need to fix so that highlighting of the submit vs. next exercise buttons is not score-dependent when the workout policy says it shouldn't be.  This is already done for MC questions, but needs to be fixed for coding questions.

**Comment by pmk1433** [comment]
I have been mauled horribly by this issue.

**Comment by pmk1433** [comment]
Should this be issue be closed out since the shift of button highlighting is now the default behavior for coding questions and MCQs are auto-advanced?

**Comment by s-edwards** [comment]
Yes, this is working.
