### ISSUE TITLE
Refactor exercise/base_exercise classes and controller

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#6]
Currently, the exercise controller is the center of activity for exercises, but base_exercise is actually the central entity, with "exercise" objects actually being versions of the exercise along a history trail of edits.  It would probably be better to make BaseExercise the center for editing exercises, although we still want "exercise" to be the word used in routes.  This would require some refactoring, however.

**Comment by s-edwards** [comment]
The model classes have been completely refactored.  The exercise controller still needs to be updated, though.

**Comment by pmk1433** [comment]
Can this one be reviewed in PROD and closed out?

**Comment by s-edwards** [comment]
This issue no longer applies, and is being closed. The exercises controller is ugly and still needs refactoring at some point.
