### ISSUE TITLE
Find the latest deadline for a workout

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#62]
A method to determine the latest deadline for a workout, i.e. the date beyond which the workout is closed for all students in the course. If there are no student extensions for a workout, return the hard deadline. Else return the maximum deadline extension granted to a student enrolled in the course.

**Comment by pmk1433** [comment]
Implemented in the form two new methods in the Workout Offering model called ultimate_deadline and shutdown?

**Comment by s-edwards** [comment]
OK, but these method names, together with similar-performing methods in WorkoutScore, should be refactored to be more uniform and understandable.  We need to provide a more uniform way of accessing individual-specific values vs. "for everybody" values.  The current_deadline_distance method should be renamed as well.

**Comment by pmk1433** [comment]
Need to use it in the thumbnails and in the sidebar for conditional displays for feedback.

**Comment by pmk1433** [comment]
Isn't this one already in PROD? I remember completing a chunk of this last month.

**Comment by s-edwards** [comment]
It wasn't always working (leading to NPE in score_fix), but now does appear to be.  Closing.
