### ISSUE TITLE
Fix the Gym/WorkoutOffering conflict

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#78]
When a user has practised a exercise both as a part of the gym and the workout offering, ensure only the one for the workout offering is taken into consideration for computing the workout score.

**Comment by pmk1433** [comment]
Fixed the conflicts and verified in DEV. Was unbelievably time-consuming to weed out because of the false assumption built-in to the score_for method in the Workout class.

**Comment by ayaankazerouni** [comment]
Looks like this regressed for an LTI assignment.
