### ISSUE TITLE
Provide a way for instructors to review student work

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#81]
In the gradebook view, instructors should be able to click on individual workout scores and view the corresponding student's workout results page.  From that page, they should be able to click on individual exercise thumbnails and view the student's work for that exercise.

Later, we should think about providing access to view scores from individual workout pages, as well as from the gradebook.

**Comment by pmk1433** [comment]
Implemented and working in DEV.

**Comment by pmk1433** [comment]
Done and dusted.
