### ISSUE TITLE
The "Create your course" button on the homepage needs to be fixed

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#9]
The "Create your course" button on the homepage should be revised to be a modal with a progressive refinement-style search interface (it really means creating a course offering, with the addition of creating the associated course if necessary).  This part of the UI also needs to include conditional registration if the user hasn't registered yet.

**Comment by s-edwards** [comment]
I've fixed this to use a modal now, but at the moment it just shows a message saying the feature is disabled until a future release.  I'm reassigning this to Avalanche.

**Comment by s-edwards** [comment]
We need better control over access to course resources (i.e., the course's question bank and workouts) before we can allow unrestricted creation of new course offerings by users.  Otherwise, students could simply create new offerings and get access to everything that any instructor could see.

**Comment by ayaankazerouni** [comment]
Closing for now. Access related issues are the next step.
