### ISSUE TITLE
Fix time limit support

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#92]
* Students were able to submit attempts after the time limit expired
* Some students (3) were able to resume working on questions long after the class ended and the time limit expired.

**Comment by pmk1433** [comment]
The first new issue after I left. :')

**Comment by ayaankazerouni** [comment]
Ok, this has been dealt with. If a student acceses a workout whose time limit is passed, they are not allowed to submit attempts and an appropriate message is displayed. The countdown timer also results in the same behaviour.

Closing.
