### ISSUE TITLE
JS countdown timer on the practice page

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#96]

**Comment by pmk1433** [comment]
Ah, the Auld enemy. I remember that it works in Firefox but naught else.

**Comment by ayaankazerouni** [comment]
Ok, this is now fixed on the staging branch, commit 3d4a6b1a616da4c2c6a094ab9d25479bd3648d5c. Closing for now.

Note: Nothing happens when time runs out; that will be dealt with in issue #92.

**Comment by s-edwards** [comment]
What browsers did you test it in?  It was working in some browsers (I think, Safari), but not others (including Chrome).  Definitely test it in Safari, Chrome, and IE before closing.

**Comment by ayaankazerouni** [comment]
OK, tested in Safari, Chrome and Firefox. Will test it in IE as soon as I can get my hands on a Windows computer.

**Comment by ayaankazerouni** [comment]
Also, I will probably need to deploy to the staging server to test this out on IE (to avoid having to set up a development environment on a windows machine just to test this). But when we used the staging server last it was in the middle of JRuby Week. Can I go ahead and deploy without breaking anything?

**Comment by s-edwards** [comment]
The staging server is still set for jruby.  Add an appropriate .ruby-version file to the staging branch (specify ruby-2.0.0-p247) and check it in.  Then deploying will use MRI instead of jruby.  Try it and see if it works.  If you have any trouble, let me know.

**Comment by ayaankazerouni** [comment]
Apparently Microsoft provides free tools for IE testing on other platforms: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

It's basically a VM with nothing but IE installed. So I have now tested it on IE10 on Windows 7, and it works. I'm currently downloading the IE8-Win7 machine just to check it out on an older version, but I think we're in the clear.

**Comment by ayaankazerouni** [comment]
Ok, this is now tested on all 4 major browsers. Closing.

**Comment by s-edwards** [comment]
Awesome, thanks!

**Comment by pmk1433** [comment]
Finally, after ten months since that GRA wrote this buggy code.

**Comment by pmk1433** [comment]
@ayaankazerouni, you can in the future mention the issue number in your git commit message for the code so that the committed code automatically get linked to the issue on GitHub.

**Comment by ayaankazerouni** [comment]
Figure out bugs (possible race conditions) that students were seeing during a test.

Students saw 'no time remaining' when they were starting the workout offering, even though their workout_scores were created well before the time limit had passed.

**Comment by ayaankazerouni** [comment]
Update: this due to incorrect timezone settings on user machines. A fix is underway.

**Comment by ayaankazerouni** [comment]
We issued a fix for this right before break. Can we confirm that there have been no problems? I couldn't test it completely since my VM's time settings depended on my computer, so I couldn't quite reproduce the problem.

**Comment by s-edwards** [comment]
Agree this can be closed.
