### ISSUE TITLE
Resetting to the starter code

### ISSUE THREAD

**Issue by cashaffer** [web-cat/code-workout#98]
Many exercises have "starter" code that a student sees in the editing pane. Once a student makes changes to this code, so far as I can tell there is no way to reset to the original version. Once a student does an exercise, forever after it seems to load with the saved code that the student had done last time. There needs to be a way to get back to the start state for the exercise (a clean version of the "starter" code).

**Comment by pmk1433** [comment]
Yes, a reset button sounds good. I remember seeing the 'Forget It!' in CodingBat but never got around to discussing with my advisor about it. However, I don't understand your second sentence.

**Comment by cashaffer** [comment]
>> Once a student makes changes to this code, so far as I can tell there is no way to reset to the original 
>> version.

> However, I don't understand your second sentence.

Its just trying to explain why there is a problem when there is no "reset" button. Say that the student changes the starter code, perhaps breaking it beyond recognition. He/she decides to start over from scratch, with clean starter code. But there seems to be no way to do this.

**Comment by ayaankazerouni** [comment]
This is now implemented in the staging branch. It should be merged into production soon. Pictures of the reset procedure are attached. Closing for now. Please reopen the issue if you want something changed/fixed.

### Screenshots
**User has written incorrect code and wants to reset to starter code**
![before-reset](https://cloud.githubusercontent.com/assets/11241828/19657875/cf0a01d2-99f3-11e6-99f0-18afd94444fe.png)

**User hits the reset button and is presented with a warning that their current work will be lost.***
![during-reset](https://cloud.githubusercontent.com/assets/11241828/19657876/cf0a097a-99f3-11e6-9118-6b55c7aeab5c.png)

**The editor after the reset is complete.**
![after-reset](https://cloud.githubusercontent.com/assets/11241828/19657874/cf0354e0-99f3-11e6-8a67-b858c33b9a6d.png)

**Comment by s-edwards** [comment]
Change the text on the button to simply "Reset".  The term "starter code" has no meaning to end users.
